# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e73ce6f8aac99ba70f1d2fc135345e8e171d0e0040d760762cdcb0add71e28c3e4f49808f5a054b7a11950f8bfc7887892207c45caed29ba463f2a2e72ef0efc

test:
  secret_key_base: 3d296b93785af2180aca0174c985b13e4d8ffd34566eaecb1626ab0488aedfaa44f42392020fc53b03148aef3f453bcdcbf5065e10397cbf412ebc306d97c9c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
